### ISSUE TITLE
html

### ISSUE THREAD

**Issue by rajasekaranmcait** [kilkelly/react-passport-redux-example#1]
awesome project..hatts of you for this project i am using now..in this project i want to render DOM via UI library in html..so how to create main html file for render?!

**Comment by kilkelly** [comment]
Hi there, I'm wondering why you need to use a UI library when you can accomplish so much of the same functionality using React?

Which UI library are you using?

**Comment by rajasekaranmcait** [comment]
commonly most of them searching where is UI library from html file for rendering..so as per the way just i am searching where is html file..after that only i got it from index.js through devStart.js, but i know its not a mandatory one and also its not an issue..thank u for ur valuable reply kilkelly

**Comment by rajasekaranmcait** [comment]
Hi Kilkelly thank u for ur reply..its my doubt only..its not an issue
actually..
commonly most of them searching where is UI library from html file for
rendering..so as per the way just i am searching where is html file..after
that only i got it from index.js through devStart.js, but i know its not a
mandatory one..
i am eagerly learning react now..it may be difficult for starters to
understand for me this..

Thanks & Regards,
Rajasekaran

**Comment by kilkelly** [comment]
I think I understand now. The HTML used during rendering is in /src/server/index.js
https://github.com/kilkelly/react-passport-redux-example/blob/master/src/server/index.js#L67-L85

You can add links to any UI libraries you wish to use into this HTML and they should work fine. Just don't touch this line of HTML as it is important for rendering:

`<div id="app"></div>`

> i am eagerly learning react now..

I am learning also Rajasekaran. Learn a small bit everyday and in a few months you can look back at your old code and see how much better your new code is :) 
Kind regards!

**Comment by rajasekaranmcait** [comment]
Yeah sure Kilkelly..You are right what you say..i feel day by day improved
my learning surely..
I want one more help from you if you possible means..
I did a project for user authentication(login&register) using
- angularjs -nodejs  -passport -mongodb

This same project i want to do in React from angular(dont use angular now).
Thats why i trying to refer your this project, but i can't :'(
Need to do in react without redux..
pls help me in reactjs..

my github project repo is :

https://github.com/rajasekaranmcait/user-login-authentication

Thanks & Regards,
Rajasekaran
