### ISSUE TITLE
No 'public/assets' folder generated

### ISSUE THREAD

**Issue by terrorgeek** [kilkelly/react-passport-redux-example#3]
Hi Kilkelly, 
   I saw the webpack dev and prod config file and it should create the public/assets folder under any enviroument right?  but after I ran both there was still nothing like 'public/assets' created, interestingly, the project is running good.

**Comment by kilkelly** [comment]
Hi @painforever the webpack dev version could be creating that folder in memory. The production version should definitely be creating the public/assets folder however. What environment are you running it in? Sorry for the very late reply.
